version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name : mysqls
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE

    ports:
      #- $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
      - $MYSQL_PORT:$MYSQL_PORT
    expose:
      - $MYSQL_PORT

    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3030:3030
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DBNAME=$MYSQL_DBNAME
      - MYSQL_PORT=$MYSQL_PORT
      - DATABASE_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@$MYSQL_HOST:$MYSQL_PORT/$MYSQL_DBNAME
    stdin_open: true
    tty: true
    command : bash -c "npx npm run start:prod"

volumes: 
  db: